spring:
  application:
    name: springbootStart
  datasource:
    url: jdbc:sqlite:./db/magic-packet.db
    driver-class-name: org.sqlite.JDBC
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
server:
  port: 8081
  servlet:
    context-path: /magic
    encoding:
      force: true
      charset: utf-8
      enabled: true
  max-http-header-size: 10MB