spring:
  application:
    name: springbootStart
  datasource:
    url: jdbc:sqlite:D:\magic-packet.db
    driver-class-name: org.sqlite.JDBC
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 200
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM sqlite_master
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: slf4j,wall,stat
      filter:
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
        wall:
          enabled: true
          config:
            create-table-allow: false
            drop-table-allow: false
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
      stat-view-servlet:
        enabled: false
      socket-timeout: 30000
      connect-timeout: 2000
      keep-alive: true
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
  servlet:
    context-path: /magic
    encoding:
      force: true
      charset: utf-8
      enabled: true
  max-http-header-size: 10MB